### ISSUE TITLE
Crash Report - chan receive?

### ISSUE THREAD

**Issue by cdelorme** [cdelorme/level#4]
Encountering a bug that appears to stem from a receiving channel processing the crc32 summary:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x4b449b]

goroutine 5 [running]:
hash/crc32.update(0x0, 0x0, 0xc208013200, 0x689, 0x889, 0xc2080466c0)
/home/vagrant/.gvm/gos/go1.4.2/src/hash/crc32/crc32.go:104 +0x5b
hash/crc32.updateCastagnoli(0x7f8d00000000, 0xc208013200, 0x689, 0x889, 0x0)
/home/vagrant/.gvm/gos/go1.4.2/src/hash/crc32/crc32_amd64x.go:26 +0x7d
hash/crc32.Update(0xc200000000, 0x0, 0xc208013200, 0x689, 0x889, 0x889)
/home/vagrant/.gvm/gos/go1.4.2/src/hash/crc32/crc32.go:112 +0x55
hash/crc32.(*digest).Write(0xc208ac8e60, 0xc208013200, 0x689, 0x889, 0x889, 0x0, 0x0)
/home/vagrant/.gvm/gos/go1.4.2/src/hash/crc32/crc32.go:118 +0x62
github.com/cdelorme/level6/l6.func·001(0x0)
/home/vagrant/.gvm/pkgsets/go1.4.2/global/src/github.com/cdelorme/level6/l6/level6.go:102 +0x64d
created by github.com/cdelorme/level6/l6.(*Level6).HashAndCompare
/home/vagrant/.gvm/pkgsets/go1.4.2/global/src/github.com/cdelorme/level6/l6/level6.go:110 +0x24e

goroutine 1 [chan send]:
github.com/cdelorme/level6/l6.(*Level6).HashAndCompare(0xc20803ca90)
/home/vagrant/.gvm/pkgsets/go1.4.2/global/src/github.com/cdelorme/level6/l6/level6.go:125 +0x43f
main.main()
/home/vagrant/.gvm/pkgsets/go1.4.2/global/src/github.com/cdelorme/level6/main.go:95 +0x14e9

goroutine 6 [runnable]:
syscall.Syscall(0x0, 0x4, 0xc20836c000, 0x20f, 0xf, 0x20f, 0x0)
/home/vagrant/.gvm/gos/go1.4.2/src/syscall/asm_linux_amd64.s:21 +0x5
syscall.read(0x4, 0xc20836c000, 0x20f, 0x20f, 0xc2080d8c00, 0x0, 0x0)
/home/vagrant/.gvm/gos/go1.4.2/src/syscall/zsyscall_linux_amd64.go:867 +0x6e
syscall.Read(0x4, 0xc20836c000, 0x20f, 0x20f, 0x507580, 0x0, 0x0)
/home/vagrant/.gvm/gos/go1.4.2/src/syscall/syscall_unix.go:136 +0x58
os.(*File).read(0xc2085cc000, 0xc20836c000, 0x20f, 0x20f, 0x70, 0x0, 0x0)
/home/vagrant/.gvm/gos/go1.4.2/src/os/file_unix.go:191 +0x5e
os.(*File).Read(0xc2085cc000, 0xc20836c000, 0x20f, 0x20f, 0x7f8d7fece098, 0x0, 0x0)
/home/vagrant/.gvm/gos/go1.4.2/src/os/file.go:95 +0x91
bytes.(*Buffer).ReadFrom(0xc208ae0000, 0x7f8d7fcec970, 0xc2085cc000, 0x0, 0x0, 0x0)
/home/vagrant/.gvm/gos/go1.4.2/src/bytes/buffer.go:169 +0x25a
io/ioutil.readAll(0x7f8d7fcec970, 0xc2085cc000, 0x20f, 0x0, 0x0, 0x0, 0x0, 0x0)
/home/vagrant/.gvm/gos/go1.4.2/src/io/ioutil/ioutil.go:33 +0x1b0
io/ioutil.ReadFile(0xc2080d8c00, 0x72, 0x0, 0x0, 0x0, 0x0, 0x0)
/home/vagrant/.gvm/gos/go1.4.2/src/io/ioutil/ioutil.go:70 +0x1b5
github.com/cdelorme/level6/l6.func·001(0x1)
/home/vagrant/.gvm/pkgsets/go1.4.2/global/src/github.com/cdelorme/level6/l6/level6.go:95 +0x3db
created by github.com/cdelorme/level6/l6.(*Level6).HashAndCompare
/home/vagrant/.gvm/pkgsets/go1.4.2/global/src/github.com/cdelorme/level6/l6/level6.go:110 +0x24e

goroutine 7 [chan receive]:
github.com/cdelorme/level6/l6.func·002()
/home/vagrant/.gvm/pkgsets/go1.4.2/global/src/github.com/cdelorme/level6/l6/level6.go:117 +0x7b
created by github.com/cdelorme/level6/l6.(*Level6).HashAndCompare
/home/vagrant/.gvm/pkgsets/go1.4.2/global/src/github.com/cdelorme/level6/l6/level6.go:120 +0x353
```

**Comment by cdelorme** [comment]
Moved to synchronous process and plans to cleanup and reimplement async behavior.
